import type { OverlayStyling } from './types'

export interface StylePreset {
  id: string
  name: string
  description: string
  styling: OverlayStyling
}

export const PRESETS: StylePreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Clean white on dark — timeless broadcast look',
    styling: {
      fontFamily: "'Segoe UI', sans-serif",
      fontSize: 28,
      fontWeight: 600,
      textColor: '#ffffff',
      backgroundColor: '#1a1a2e',
      backgroundStyle: 'solid',
      accentColor: '#667eea',
      borderRadius: 8,
      animation: 'slide',
      autoHideSeconds: 8,
    },
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Glassmorphism with blur effect',
    styling: {
      fontFamily: "'Inter', sans-serif",
      fontSize: 26,
      fontWeight: 600,
      textColor: '#ffffff',
      backgroundColor: '#000000',
      backgroundStyle: 'glass',
      accentColor: '#8b5cf6',
      borderRadius: 12,
      animation: 'fade',
      autoHideSeconds: 8,
    },
  },
  {
    id: 'broadcast-news',
    name: 'Broadcast News',
    description: 'Bold red accent bar — news ticker style',
    styling: {
      fontFamily: "'Arial', sans-serif",
      fontSize: 30,
      fontWeight: 700,
      textColor: '#ffffff',
      backgroundColor: '#0d1b2a',
      backgroundStyle: 'accent-bar',
      accentColor: '#e63946',
      borderRadius: 0,
      animation: 'slide',
      autoHideSeconds: 10,
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Serif font with warm gold accents',
    styling: {
      fontFamily: "'Georgia', serif",
      fontSize: 28,
      fontWeight: 400,
      textColor: '#fdf6e3',
      backgroundColor: '#2d2d2d',
      backgroundStyle: 'gradient',
      accentColor: '#d4a574',
      borderRadius: 4,
      animation: 'fade',
      autoHideSeconds: 10,
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professional blue gradient',
    styling: {
      fontFamily: "'Helvetica Neue', sans-serif",
      fontSize: 26,
      fontWeight: 500,
      textColor: '#ffffff',
      backgroundColor: '#1e3a5f',
      backgroundStyle: 'gradient',
      accentColor: '#3b82f6',
      borderRadius: 6,
      animation: 'rise',
      autoHideSeconds: 8,
    },
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Cyberpunk glow on dark',
    styling: {
      fontFamily: "'Montserrat', sans-serif",
      fontSize: 28,
      fontWeight: 700,
      textColor: '#00ff88',
      backgroundColor: '#0a0a0a',
      backgroundStyle: 'solid',
      accentColor: '#ff00ff',
      borderRadius: 2,
      animation: 'zoom',
      autoHideSeconds: 6,
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Subtle, barely-there overlay',
    styling: {
      fontFamily: "'Inter', sans-serif",
      fontSize: 24,
      fontWeight: 400,
      textColor: '#e0e0e0',
      backgroundColor: '#1a1a1a',
      backgroundStyle: 'glass',
      accentColor: '#666666',
      borderRadius: 16,
      animation: 'fade',
      autoHideSeconds: 6,
    },
  },
  {
    id: 'sports',
    name: 'Sports',
    description: 'High-energy with sharp angles',
    styling: {
      fontFamily: "'Arial', sans-serif",
      fontSize: 32,
      fontWeight: 800,
      textColor: '#ffffff',
      backgroundColor: '#1a1a2e',
      backgroundStyle: 'accent-bar',
      accentColor: '#f59e0b',
      borderRadius: 0,
      animation: 'slide',
      autoHideSeconds: 8,
    },
  },
  {
    id: 'recital',
    name: 'Dance Recital',
    description: 'Warm and inviting for performance events',
    styling: {
      fontFamily: "'Playfair Display', serif",
      fontSize: 30,
      fontWeight: 700,
      textColor: '#ffffff',
      backgroundColor: '#2d1b3d',
      backgroundStyle: 'gradient',
      accentColor: '#e879a8',
      borderRadius: 10,
      animation: 'rise',
      autoHideSeconds: 10,
    },
  },
  {
    id: 'church',
    name: 'Church/Worship',
    description: 'Calm and reverent with soft tones',
    styling: {
      fontFamily: "'Georgia', serif",
      fontSize: 28,
      fontWeight: 400,
      textColor: '#f0ead6',
      backgroundColor: '#1a2332',
      backgroundStyle: 'solid',
      accentColor: '#8b9dc3',
      borderRadius: 6,
      animation: 'fade',
      autoHideSeconds: 12,
    },
  },
]
